import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        Primary50: "var(--color-primary-50)",
        Primary100: "var(--color-primary-100)",
        Primary200: "var(--color-primary-200)",
        Primary300: "var(--color-primary-300)",
        Primary400: "var(--color-primary-400)",
        Primary500: "var(--color-primary-500)",
        Primary600: "var(--color-primary-600)",
        Primary700: "var(--color-primary-700)",
        Primary800: "var(--color-primary-800)",
        Primary900: "var(--color-primary-900)",
        Primary1000: "var(--color-primary-1000)",
        Black5: "var(--color-black-5)",
        Black10: "var(--color-black-10)",
        Black20: "var(--color-black-20)",
        Black30: "var(--color-black-30)",
        Black40: "var(--color-black-40)",
        Black50: "var(--color-black-50)",
        Black60: "var(--color-black-60)",
        Black70: "var(--color-black-70)",
        Black80: "var(--color-black-80)",
        Black90: "var(--color-black-90)",
        Black100: "var(--color-black-100)",
        Gray50: "var(--color-gray-50)",
        Gray100: "var(--color-gray-100)",
        Gray200: "var(--color-gray-200)",
        Gray300: "var(--color-gray-300)",
        Gray400: "var(--color-gray-400)",
        Gray500: "var(--color-gray-500)",
        Gray600: "var(--color-gray-600)",
        Gray700: "var(--color-gray-700)",
        Gray800: "var(--color-gray-800)",
        Gray900: "var(--color-gray-900)",
        danger: "var(--color-danger)",
        dangerSoft: "var(--color-danger-soft)",
        dangerDark: "var(--color-danger-dark)",
        warningSoft: "var(--color-warning-soft)",
        warningDark: "var(--color-warning-dark)",
        warning: "var(--color-warning)",
        success: "var(--color-success)",
        successSoft: "var(--color-success-soft)",
        successDark: "var(--color-success-dark)",
      },
      width: {
        "fill-available": "-webkit-fill-available",
      },
    },
  },
  plugins: [],
};
export default config;
